### ISSUE TITLE
IndexError: index 100 is out of bounds for axis 1 with size 100

### ISSUE THREAD

**Issue by zhang-jian** [ddahlmeier/neural_lm#3]
Hi,

Thanks for sharing this.

I tried to run nce training with command line:
`python lbl_nce.py train test test -v`

However, error occurs:

```
2016-04-22 18:49:35,230 epoch 0
Traceback (most recent call last):
  File "lbl_nce.py", line 424, in <module>
    noise_data_ratio=noise_samples)
  File "lbl_nce.py", line 323, in train_lbl
    train_logp = train_model(minibatch_index)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 879, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2282, in perform
    inplace_increment(out[0], tuple(inputs[2:]), inputs[1])
IndexError: index 100 is out of bounds for axis 1 with size 100
Apply node that caused the error: AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(Alloc.0, Elemwise{Composite{(i0 / Cast{float32}(i1))}}.0, Subtensor{int64:int64:}.0, ARange{dtype='int64'}.0)
Toposort index: 67
Inputs types: [TensorType(float32, matrix), TensorType(float32, (True,)), TensorType(int32, vector), TensorType(int64, vector)]
Inputs shapes: [(10004, 100), (1,), (2500,), (2500,)]
Inputs strides: [(400, 4), (4,), (4,), (8,)]
Inputs values: ['not shown', array([-0.0004], dtype=float32), 'not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{Cast{float32}(((i0 * i1) / i2))}}[(0, 1)](TensorConstant{(1, 1) of ..3073786154}, AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0, Elemwise{Add}[(0, 0)].0)]]

Backtrace when the node is created:
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)

Debugprint of the apply node: 
AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False} [id A] <TensorType(float32, matrix)> ''   
 |Alloc [id B] <TensorType(float32, matrix)> ''   
 | |TensorConstant{(1, 1) of 0.0} [id C] <TensorType(float32, (True, True))>
 | |Shape_i{0} [id D] <TensorType(int64, scalar)> ''   
 | | |Q [id E] <TensorType(float32, matrix)>
 | |Elemwise{Composite{Switch(EQ(i0, i1), ((i2 * i3) // (-(i4 * i0))), i0)}}[(0, 0)] [id F] <TensorType(int64, scalar)> ''   
 |   |Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}}[(0, 2)] [id G] <TensorType(int64, scalar)> ''   
 |   | |Elemwise{Composite{(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3) - Switch(LT(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)))}}[(0, 1)] [id H] <TensorType(int64, scalar)> ''   
 |   | | |Elemwise{lt,no_inplace} [id I] <TensorType(int8, scalar)> ''   
 |   | | | |Elemwise{Mul}[(0, 1)] [id J] <TensorType(int64, scalar)> ''   
 |   | | | | |TensorConstant{100} [id K] <TensorType(int64, scalar)>
 |   | | | | |Elemwise{add,no_inplace} [id L] <TensorType(int64, scalar)> ''   
 |   | | | |   |TensorConstant{1} [id M] <TensorType(int64, scalar)>
 |   | | | |   |<TensorType(int64, scalar)> [id N] <TensorType(int64, scalar)>
 |   | | | |TensorConstant{0} [id O] <TensorType(int8, scalar)>
 |   | | |Elemwise{Mul}[(0, 1)] [id J] <TensorType(int64, scalar)> ''   
 |   | | |Shape_i{0} [id P] <TensorType(int64, scalar)> ''   
 |   | | | |<TensorType(int32, matrix)> [id Q] <TensorType(int32, matrix)>
 |   | | |TensorConstant{0} [id O] <TensorType(int8, scalar)>
 |   | | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | | |Elemwise{lt,no_inplace} [id S] <TensorType(int8, scalar)> ''   
 |   | | | |Elemwise{mul,no_inplace} [id T] <TensorType(int64, scalar)> ''   
 |   | | | | |TensorConstant{100} [id K] <TensorType(int64, scalar)>
 |   | | | | |<TensorType(int64, scalar)> [id N] <TensorType(int64, scalar)>
 |   | | | |TensorConstant{0} [id O] <TensorType(int8, scalar)>
 |   | | |Elemwise{mul,no_inplace} [id T] <TensorType(int64, scalar)> ''   
 |   | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | |Elemwise{Composite{((i0 * i1 * i2) // (-(i1 * i2 * i0)))}} [id U] <TensorType(int64, scalar)> ''   
 |   |   |Shape_i{1} [id V] <TensorType(int64, scalar)> ''   
 |   |   | |R [id W] <TensorType(float32, matrix)>
 |   |   |Elemwise{Composite{(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3) - Switch(LT(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)))}}[(0, 1)] [id H] <TensorType(int64, scalar)> ''   
 |   |   |Shape_i{1} [id X] <TensorType(int64, scalar)> ''   
 |   |     |<TensorType(int32, matrix)> [id Q] <TensorType(int32, matrix)>
 |   |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   |Elemwise{Composite{Switch(EQ(i0, i1), ((i0 * i2 * i3) // (i4 * i0 * i3 * i2)), i0)}} [id Y] <TensorType(int64, scalar)> ''   
 |   | |Shape_i{2} [id Z] <TensorType(int64, scalar)> ''   
 |   | | |C [id BA] <TensorType(float32, 3D)>
 |   | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | |Shape_i{0} [id BB] <TensorType(int64, scalar)> ''   
 |   | | |C [id BA] <TensorType(float32, 3D)>
 |   | |Shape_i{1} [id BC] <TensorType(int64, scalar)> ''   
 |   | | |C [id BA] <TensorType(float32, 3D)>
 |   | |TensorConstant{-1} [id BD] <TensorType(int64, scalar)>
 |   |Elemwise{Composite{Switch(EQ(i0, i1), ((i2 * i3 * i0) // (i4 * i2 * i3 * i0)), i0)}} [id BE] <TensorType(int64, scalar)> ''   
 |   | |Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}}[(0, 2)] [id G] <TensorType(int64, scalar)> ''   
 |   | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | |Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}} [id BF] <TensorType(int64, scalar)> ''   
 |   | | |Shape_i{1} [id X] <TensorType(int64, scalar)> ''   
 |   | | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | | |Elemwise{Composite{((i0 * i1 * i2) // (-(i1 * i2 * i0)))}} [id U] <TensorType(int64, scalar)> ''   
 |   | |Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}} [id BG] <TensorType(int64, scalar)> ''   
 |   | | |Shape_i{1} [id V] <TensorType(int64, scalar)> ''   
 |   | | |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |   | | |Elemwise{Composite{((i0 * i1 * i2) // (-(i1 * i2 * i0)))}} [id U] <TensorType(int64, scalar)> ''   
 |   | |TensorConstant{-1} [id BD] <TensorType(int64, scalar)>
 |   |Shape_i{2} [id Z] <TensorType(int64, scalar)> ''   
 |Elemwise{Composite{(i0 / Cast{float32}(i1))}} [id BH] <TensorType(float32, (True,))> ''   
 | |TensorConstant{(1,) of -1.0} [id BI] <TensorType(float32, (True,))>
 | |InplaceDimShuffle{x} [id BJ] <TensorType(int64, (True,))> ''   
 |   |Elemwise{Composite{(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1) - Switch(LT(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i4, i1, i2), i1), i2), i1), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1)), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i4, i1, i2), i1), i2), i1), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1)))}}[(0, 0)] [id BK] <TensorType(int64, scalar)> ''   
 |     |Elemwise{mul,no_inplace} [id BL] <TensorType(int64, scalar)> ''   
 |     | |TensorConstant{2500} [id BM] <TensorType(int64, scalar)>
 |     | |Elemwise{add,no_inplace} [id L] <TensorType(int64, scalar)> ''   
 |     |TensorConstant{0} [id O] <TensorType(int8, scalar)>
 |     |Shape_i{0} [id BN] <TensorType(int64, scalar)> ''   
 |     | |<TensorType(int32, vector)> [id BO] <TensorType(int32, vector)>
 |     |TensorConstant{-1} [id R] <TensorType(int8, scalar)>
 |     |Elemwise{mul,no_inplace} [id BP] <TensorType(int64, scalar)> ''   
 |       |TensorConstant{2500} [id BM] <TensorType(int64, scalar)>
 |       |<TensorType(int64, scalar)> [id N] <TensorType(int64, scalar)>
 |Subtensor{int64:int64:} [id BQ] <TensorType(int32, vector)> ''   
 | |<TensorType(int32, vector)> [id BO] <TensorType(int32, vector)>
 | |ScalarFromTensor [id BR] <int64> ''   
 | | |Elemwise{mul,no_inplace} [id BP] <TensorType(int64, scalar)> ''   
 | |ScalarFromTensor [id BS] <int64> ''   
 |   |Elemwise{mul,no_inplace} [id BL] <TensorType(int64, scalar)> ''   
 |ARange{dtype='int64'} [id BT] <TensorType(int64, vector)> ''   
   |TensorConstant{0} [id O] <TensorType(int8, scalar)>
   |Elemwise{Composite{(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1) - Switch(LT(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i4, i1, i2), i1), i2), i1), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1)), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i4, i1, i2), i1), i2), i1), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(LT(i0, i1), (i0 + i2), i0)}(i0, i1, i2), i1, i3), i2), i1)))}}[(0, 0)] [id BK] <TensorType(int64, scalar)> ''   
   |TensorConstant{1} [id BU] <TensorType(int8, scalar)>

Storage map footprint:
 - <TensorType(int32, vector)>, Shared Input, Shape: (27561200,), ElemSize: 4 Byte(s), TotalSize: 110244800 Byte(s)
 - <TensorType(int32, matrix)>, Shared Input, Shape: (1102448, 2), ElemSize: 4 Byte(s), TotalSize: 8819584 Byte(s)
 - <TensorType(int32, vector)>, Shared Input, Shape: (1102448,), ElemSize: 4 Byte(s), TotalSize: 4409792 Byte(s)
 - AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0, Shape: (10004, 100), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - Elemwise{Add}[(0, 0)].0, Shape: (10004, 100), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - Q, Shared Input, Shape: (10004, 100), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - R, Shared Input, Shape: (10004, 100), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - Q.T, Shape: (100, 10004), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - Alloc.0, Shape: (10004, 100), ElemSize: 4 Byte(s), TotalSize: 4001600 Byte(s)
 - Reshape{2}.0, Shape: (200, 100), ElemSize: 4 Byte(s), TotalSize: 80000 Byte(s)
 - Reshape{2}.0, Shape: (100, 200), ElemSize: 4 Byte(s), TotalSize: 80000 Byte(s)
 - C, Shared Input, Shape: (2, 100, 100), ElemSize: 4 Byte(s), TotalSize: 80000 Byte(s)
 - b, Shared Input, Shape: (10004,), ElemSize: 4 Byte(s), TotalSize: 40016 Byte(s)
 - Reshape{2}.0, Shape: (100, 100), ElemSize: 4 Byte(s), TotalSize: 40000 Byte(s)
 - ARange{dtype='int64'}.0, Shape: (2500,), ElemSize: 8 Byte(s), TotalSize: 20000 Byte(s)
 - Subtensor{int64:int64:}.0, Shape: (2500,), ElemSize: 4 Byte(s), TotalSize: 10000 Byte(s)
 - ARange{dtype='int64'}.0, Shape: (100,), ElemSize: 8 Byte(s), TotalSize: 800 Byte(s)
 - Reshape{1}.0, Shape: (200,), ElemSize: 4 Byte(s), TotalSize: 800 Byte(s)
 - Subtensor{int64:int64:}.0, Shape: (100,), ElemSize: 4 Byte(s), TotalSize: 400 Byte(s)
 - MakeVector{dtype='int64'}.0, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - MakeVector{dtype='int64'}.0, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - TensorConstant{[10004     1]}, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{Composite{(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3) - Switch(LT(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i5, i6, i2), i3), i2), i3), Composite{Switch(LT(i0, i1), i1, i0)}(Composite{Switch(GE(i0, i1), i1, i0)}(Composite{Switch(LT(i0, i1), i2, i0)}(Composite{Switch(i0, (i1 + i2), i1)}(i0, i1, i2), i3, i4), i2), i3)))}}[(0, 1)].0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{Composite{Switch(EQ(i0, i1), ((i2 * i3 * i0) // (i4 * i2 * i3 * i0)), i0)}}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Elemwise{Composite{Switch(EQ(i0, i1), ((i0 * i2 * i3) // (i4 * i0 * i3 * i2)), i0)}}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{1}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1,) of -1}, Shape: (1,), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - <TensorType(int64, scalar)>, Input, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Shape_i{1}.0, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{2500}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{(1, 1) of ..3073786154}, Shape: (1, 1), ElemSize: 8 Byte(s), TotalSize: 8 Byte(s)
 - TensorConstant{100}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - TensorConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{(1,) of -1.0}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{-1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - Elemwise{Composite{(-(i0 / i1))}}[(0, 0)].0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - Elemwise{Cast{float32}}.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - TensorConstant{(1, 1) of 2.71828}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 0.0}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - Elemwise{Composite{(i0 / Cast{float32}(i1))}}.0, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{0}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{-1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 - TensorConstant{1}, Shape: (), ElemSize: 1 Byte(s), TotalSize: 1.0 Byte(s)
 TotalSize: 143823987.0 Byte(s) 0.134 GB
 TotalSize inputs: 131597487.0 Byte(s) 0.123 GB
```

Do you get the same error, or did I miss anything?

Thanks,

**Comment by ddahlmeier** [comment]
Hi, the NCE implementation is incomplete and not working. I had started on it but did not have time to complete it. Sorry for that.
